FRONT-END-BOOTCAMP-PLUS-4/gamechu

- prisma/generated/package.json
- prisma/generated/schema.prisma
- prisma/schema.prisma
- prisma/seed.ts
- prisma/test.ts
DB에 데이터 저장 로직
-   [x] IGDB API를 통해 DB에 데이터를 저장하기 위한 seed.ts를 작성하였습니다.
close #13
> [feat/#13]: 데이터 저장을 위한 seed 작성

- app/components/Button.tsx
- app/layout.tsx
- app/test/button-test/page.tsx
- package-lock.json
- package.json
- tailwind.config.ts
- utils/tailwindUtil.ts
버튼 컴포넌트, 테스트 페이지 
-   [x] 버튼 컴포넌트 생성
-   [x] className을 조건부로 처리할 때 코드가 복잡해지는 걸 줄이기 위해 `cn()` 유틸 함수 추가
-   [ ] 정상적으로 동작하는지 직접 테스트해봤나요?
-   [ ] 기능 추가/수정 후 UI나 비즈니스 로직에 영향은 없나요?
close #19
> [feat/#19] 버튼 컴포넌트

- app/components/Input/Input.tsx
인풋 컴포넌트 구현
-   [x] 인풋 공통 컴포넌트를 구현하였습니다.
-   [ ] tailwindcss 잘 작성됐는지 확인 부탁드립니다.
사용예시입니다.
```tsx
<Input placeholder="이름을 입력하세요" variant="filled" />
<Input
placeholder="이메일을 입력하세요"
hasError={true}
renderRight={<span>!</span>}
variant="outlined"
/>
<Input placeholder="비밀번호를 입력하세요" variant="filled" />
<Input
placeholder="비밀번호를 다시 입력하세요"
variant="outlined"
/>
<Input
placeholder="검색어를 입력하세요"
variant="filled"
renderRight={
<button className="text-white font-semibold">🔍</button>
}
/>
<Input
type="number"
placeholder="나이를 입력하세요"
variant="outlined"
/>
```
close #20
> [Feat/#20] 인풋 컴포넌트 구현

- app/components/Pager.tsx
- app/test/pager/page.tsx
페이저 컴포넌트 구현 및 테스트 페이지 작성
-   [x] 스타일링 제대로 되어있는지 확인해주세요
한 페이지에 몇개의 아이템을 받아올 것인지, 총 몇 개의 페이지까지 한번에 보여줄 것인지에 대한 설정은 페이지별로 따로 하셔야 합니다.
자세한 내용은 테스트 페이지를 참고해주세요.
close #33
> [feat/#33] Pager 컴포넌트 및 테스트 페이지 구현

- app/(base)/arena/[id]/page.tsx
- app/(base)/arena/components/ArenaChatting.tsx
- app/api/arenas/[id]/chattings/route.ts
- backend/chatting/application/usecase/FindChattingUsecase.ts
- backend/chatting/application/usecase/SendChattingUsecase.ts
- backend/chatting/application/usecase/dto/ChattingDto.ts
- backend/chatting/domain/repositories/ChattingRepository.ts
- backend/chatting/infra/repositories/prisma/PrismaChattingRepository.ts
채팅 기능 백엔드 작업
-   [x] 채팅 기능의 dto, usecase, repository 등 백엔드를 구현 하였습니다.
close #46
> [Feat/#46] 채팅 백엔드 구현

- app/components/Header.tsx
* 헤더 컴포넌트 수정
-   [x] auth-user 쿠키 삭제에 따른 헤더 컴포넌트 버그 수정
close #57
> [fix/#57]: 헤더 수정

- app/(base)/arena/[id]/components/ArenaDetailVote.tsx
- app/(base)/arena/components/ArenaIntroCard.tsx
- app/(base)/arena/components/ArenaSectionHeader.tsx
- app/(base)/arena/components/CompleteArenaCard.tsx
- app/(base)/arena/components/CompleteArenaSection.tsx
- app/(base)/arena/components/DebatingArenaCard.tsx
- app/(base)/arena/components/DebatingArenaSection.tsx
- app/(base)/arena/components/RecruitingArenaCard.tsx
- app/(base)/arena/components/RecruitingArenaSection.tsx
- app/(base)/arena/components/VoteStatusBar.tsx
- app/(base)/arena/components/VotingArenaCard.tsx
- app/(base)/arena/components/VotingArenaSection.tsx
- app/(base)/arena/components/WaitingArenaCard.tsx
- app/(base)/arena/components/WaitingArenaSection.tsx
- app/(base)/arena/page.tsx
- app/components/TierBadge.tsx
- public/icons/arena2-white.svg
- public/icons/arrowLink.svg
투기장 탐색 페이지 퍼블리싱. API 연결 없이 더미 데이터로 형태만 잡아뒀습니다.
-   [x] 투기장 탐색 페이지 퍼블리싱
-   [x] 하위 컴포넌트 생성
준선님꼐서 작성하신 아레나 상세 페이지에서 투표 상태 바를 컴포넌트(arena/components에 있음)로 분리해뒀습니다.
* 투표 상태 바 컴포넌트 호출 방식
```
<VoteStatusBar leftPercent={leftPercent} />
```
close #68
> [feat/#68] 투기장 탐색 페이지 퍼블리싱

- backend/chatting/application/usecase/dto/ChattingDto.ts
- hooks/useArenaChatManagement.ts
채팅 관련 버그 수정
-   [x] ChattingDto에서 challengerId의 type을 number만 있게 수정하였습니다.
-   [x] status가 3이상인 경우 모두 채팅을 불러오도록 수정하였습니다.
close #85
> [fix/#85] 채팅 관련 버그 수정

- app/(base)/game/[gameId]/components/GameTitleCard.tsx
- app/(base)/game/[gameId]/page.tsx
- app/(base)/game/components/GameCard.tsx
- app/(base)/profile/components/MemberReviewItem.tsx
- app/(base)/profile/components/tabs/ProfileWishlistTab.tsx
- app/(base)/profile/page.tsx
- app/api/member/wishlists/route.ts
- backend/wishlist/application/usecase/AddToWishlistUsecase.ts
- backend/wishlist/application/usecase/GetWishlistGamesUsecase.ts
- backend/wishlist/application/usecase/RemoveFromWishlistUsecase.ts
- backend/wishlist/application/usecase/dto/GetWishListGameDto.ts
- backend/wishlist/domain/repositories/WishListRepository.ts
- backend/wishlist/infra/repositories/prisma/PrismaWishListRepository.ts
* 위시리스트 관련 API 추가 및 프로필 페이지(위시리스트 목록) 디자인
-   [x] 위시리스트 조회 API 
-   [x] 위시리스트 등록 API
-   [x] 위시리스트 삭제 API
* 위시리스트 조회 API 실사용 디자인(3*2로 페이지네이션)
* 위시리스트 등록 이전
* 위시리스트 등록 이후
-   [ ] 정상적으로 동작하는지 직접 테스트해봤나요?
-   [ ] 기능 추가/수정 후 UI나 비즈니스 로직에 영향은 없나요?
close #81
> [API/#81]: 위시리스트 API 생성 및 기타 기능 추가

- app/(base)/arena/[id]/components/ArenaDetailChatList.tsx
- app/(base)/arena/[id]/components/ArenaDetailContainer.tsx
- app/(base)/arena/[id]/components/ArenaDetailHeader.tsx
- app/(base)/arena/[id]/components/ArenaDetailInputBox.tsx
- app/api/arenas/[id]/chattings/route.ts
- backend/chatting/application/usecase/SendChattingUsecase.ts
- backend/chatting/application/usecase/dto/ChattingDto.ts
- backend/chatting/domain/repositories/ChattingRepository.ts
- backend/chatting/infra/repositories/prisma/PrismaChattingRepository.ts
- hooks/useArenaChatManagement.ts
- hooks/useArenaSocket.ts
- server.ts
- utils/ErrorHandling.ts
채팅 유효성 검사 구현
-   [x] 일정 글자 수 또는 횟수 이상으로 채팅을 칠 수 없도록 백엔드 및 프론트에서 제한하도록 기능을 구현합니다.
-   [x] 일부 css 및 하드코딩 된 부분 수정하였습니다.
close #71
> [Feat/#71] 채팅 유효성 검사 구현

- app/api/arenas/[id]/route.ts
- app/api/arenas/route.ts
- app/api/member/arenas/route.ts
- app/api/member/notifications/[id]/route.ts
- app/api/member/notifications/route.ts
- app/api/notifications/route.ts
- backend/notification-record/infra/repositories/prisma/PrismaNotificationRecordRepository.ts
- utils/auth.ts
- utils/jwt.ts
알림 기록 조회, 생성, 삭제 API 구현
에러 메시지 구조 통일
에러 메시지 구조 통일하는게 좋을듯 합니다. (추후 리팩토링때 구체적으로 정하기!)
close #55
> [feat/#55] 알림 기록 API 구현

- app/(auth)/log-in/page.tsx
- app/(base)/layout.tsx
- app/(base)/page.tsx
- app/(base)/profile/components/PointHistoryCard.tsx
- app/(base)/profile/components/tabs/ProfilePointHistoryTab.tsx
- app/(base)/profile/components/tabs/ProfileReviewTab.tsx
- app/(base)/profile/components/tabs/ProfileWishlistTab.tsx
- app/components/Header.tsx
- app/components/HeaderWrapper.tsx
- app/components/LandingCard.tsx
- backend/arena/application/usecase/dto/GetArenaDto.ts
- backend/arena/domain/repositories/filters/ArenaFilters.ts
* 랜딩 페이지 SSG 적용 및 마이페이지 관련 컴포넌트 디자인 수정
-   [x] 랜딩 페이지 SSG 코드 수정 및 베이스 레이아웃 코드 수정
-   [x] 로그인 페이지 레이아웃 시프트 오류 수정
-   [x] 포인트 히스토리 컴포넌트 디자인 수정(보더라인 없애고 색상도 리뷰 아이템 색상이랑 동일화 시킴)
-   [x] PR 리뷰어가 중점적으로 확인하면 좋을 부분은?
* 현재 빌드가 안되는 상황이라 실제 SSG로 빌드되는지는 확인이 필요함
close #106
> [File/#106]: 랜딩 페이지 SSG 적용 및 마이페이지 관련 컴포넌트 디자인 수정

- app/(base)/games/[gameId]/components/CommentCard.tsx
- app/(base)/games/[gameId]/components/CommentListSSR.tsx
- app/(base)/games/[gameId]/components/GameTitleCardBase.tsx
- app/(base)/games/[gameId]/components/WishlistButtonClient.tsx
- app/(base)/games/[gameId]/page.tsx
- backend/game/infra/repositories/prisma/GamePrismaRepository.ts
- backend/review/infra/repositories/prisma/PrismaReviewRepository.ts
- backend/score-policy/application/usecase/ApplyArenaScoreUsecase.ts
- backend/score-policy/application/usecase/ApplyReviewScoreUsecase.ts
- backend/score-record/application/usecase/dto/CreateScoreRecordDto.ts
- backend/score-record/application/usecase/dto/ScoreRecordDto.ts
- backend/score-record/infra/repositories/prisma/PrismaScoreRecordRepository.ts
- prisma/schema.prisma
리뷰삭제시 actualscore get
-   [x] score 관련 작업 시 actualscore로 실제 점수 변경을 받아옵니다
-   [x] ssr아직 미구현입니다
-   [ ] 정상적으로 동작하는지 직접 테스트해봤나요?
-   [ ] 기능 추가/수정 후 UI나 비즈니스 로직에 영향은 없나요?
close #112
> [feat/#112] actualscore 관련 작업

- app/(base)/layout.tsx
- app/(base)/profile/components/PointHistoryCard.tsx
- app/(base)/profile/components/tabs/ProfilePointHistoryTab.tsx
- app/api/member/attend/route.ts
- app/components/GlobalAttendanceChecker.tsx
- backend/member/domain/repositories/MemberRepository.ts
- backend/member/infra/repositories/prisma/PrismaMemberRepository.ts
- backend/score-policy/application/usecase/ApplyAttendanceScoreUsecase.ts
- backend/score-policy/application/usecase/dto/ApplyAttendanceScoreDto.ts
- backend/score-policy/domain/ScorePolicy.ts
-   [x] 출석 기능 추가
-   [x] 포인트 히스토리 UI 수정(보더라인 없애고 색상도 다른 마이페이지 컴포넌트와 동일하게 맞춤)
-   [x] PR 리뷰어가 중점적으로 확인하면 좋을 부분은?
close #113
> [Fix/#113]: 출석 기능 추가 및 포인트 히스토리 UI 수정

- app/(base)/arenas/components/CompleteArenaSection.tsx
- app/(base)/arenas/components/DebatingArenaSection.tsx
- app/(base)/arenas/components/RecruitingArenaSection.tsx
- app/(base)/arenas/components/VotingArenaSection.tsx
- app/(base)/arenas/components/WaitingArenaSection.tsx
- backend/arena/application/usecase/GetArenaDetailUsecase.ts
- backend/arena/application/usecase/GetArenaListUsecase.ts
- backend/arena/domain/repositories/ArenaRepository.ts
- backend/arena/infra/repositories/prisma/PrismaArenaRepository.ts
- hooks/useArenaAutoStatus.ts
투기장 백엔드 리팩토링
-   [x] Repository 에서 일부 메서드의 반환타입을 Dto에서 Entity로 수정하였습니다.
-   [x] 각 section에서 상태변경 hook을 호출하도록 수정하였습니다.
close #129
> [refactor/#129] 투기장 백엔드 리팩토링

- app/(base)/profile/components/tabs/ProfileWishlistTab.tsx
- app/(base)/profile/page.tsx
- app/api/auth/[...nextauth]/route.ts
- app/api/member/profile/route.ts
- backend/wishlist/application/usecase/dto/GetWishListGameDto.ts
- backend/wishlist/infra/repositories/prisma/PrismaWishListRepository.ts
- lib/auth/authOptions.ts
- utils/GetAuthUserId.server.ts
* 각종 빌드 오류 수정
-   [x] 안 쓰는 API 제거
-   [x] next-auth API 관련 빌드 오류 수정
-   [x] 로그인 페이지, 투기장 탐색 페이지 프리렌더링 빌드 오류 수정
-   [x] 리뷰 등록 기능 버그 수정
-   [x] PR 리뷰어가 중점적으로 확인하면 좋을 부분은?
close #142
> [Fix/#142]: 빌드 오류 수정

- .github/workflows/deploy-on-ubuntu-server.yml
GitHub Actions를 활용해 CI/CD를 자동화합니다.
-   [ ] 어떤 파일을 수정했는지, 어떤 기능을 추가/변경했는지 작성
-   [ ] 필요한 경우, 왜 그렇게 구현했는지도 간단히 설명
close #149
> [build/#149]: GitHub Actions 등록

- .github/workflows/deploy-on-ubuntu-server.yml
PR event 제거 및 라벨명 수정
close #160
> [chore/#160] workflow 재수정

- app/(base)/games/[gameId]/components/ClientContentWrapper.tsx
- app/(base)/games/[gameId]/components/Comment.tsx
- app/(base)/games/[gameId]/components/CommentCard.tsx
- backend/review/infra/repositories/prisma/PrismaReviewRepository.ts
댓글 카드 프로필이미지 수정, 더보기 버튼 수정
-   [x] 댓글 카드 프로필 이미지 경로에 따라 안 나오는 문제, 프로필 사이즈 깨짐 해결
close #152
> [chore/#152] 댓글 카드 프로필 이미지 관련 오류 

- .github/workflows/deploy-on-ubuntu-server.yml
next-app-update.sh 경로 수정
close #162
> [chore/#162]: 마지막 github actions 수정

- .github/workflows/deploy-on-ubuntu-server.yml
secret에 .env 변수 업로드 및 사용
GitHub의 ubuntu-runner로 빌드 및 테스트만 진행하게 변경
close #166
> [chore/#166] GitHub Actions 구조 변경

- socket.ts
socket.ts 경로 수정
-   [x] socket.ts 경로 수정
-   [ ] 정상적으로 동작하는지 직접 테스트해봤나요?
-   [ ] 기능 추가/수정 후 UI나 비즈니스 로직에 영향은 없나요?
close #178
> [chore/#178] socket.ts 경로 수정

- app/(base)/arenas/[id]/components/ArenaDetailContainer.tsx
- app/(base)/arenas/[id]/components/ArenaDetailHeader.tsx
- app/(base)/arenas/[id]/components/ArenaDetailInfo.tsx
- app/(base)/arenas/[id]/components/ArenaDetailInputBox.tsx
- app/(base)/arenas/[id]/components/ArenaDetailRecruiting.tsx
- app/(base)/arenas/[id]/components/ArenaDetailVote.tsx
- app/(base)/arenas/[id]/components/ArenaDetailWaiting.tsx
- app/(base)/arenas/[id]/page.tsx
- app/(base)/arenas/components/CompleteArenaCard.tsx
- app/(base)/arenas/components/CompleteArenaSection.tsx
- app/(base)/arenas/components/VoteStatusBar.tsx
VoteStatusBar 투표 없음 상태 UI 개선
-  [x] voteTotalCount === 0 인 경우에 bar 색상이 꽉 차 보이지 않도록 처리
-   [x] PR 리뷰어가 중점적으로 확인하면 좋을 부분은?
close #204
> [fix/#204] VoteStatusBar 투표 없음 상태 UI 개선
